name: Deploy ScratchApp

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: PatrickSchop/AppPlatform/.github/workflows/app-deploy.yaml@main
    with:
      app-name: scratchapp-api
    secrets:
      AZURE_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}
